apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: us-central1-docker.pkg.dev/csci5409kubernetesassignment/app1-repo/app1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: "/krishna_PV_dir"
              name: shared-storage
      volumes:
        - name: shared-storage
          emptyDir: {}  # Temporary shared volume
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 6000
  type: LoadBalancer