steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/csci5409kubernetesassignment/app1-repo/app1:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/csci5409kubernetesassignment/app1-repo/app1:latest']
images:
  - 'us-central1-docker.pkg.dev/csci5409kubernetesassignment/app1-repo/app1:latest'